AllCops:
  Exclude:
    - bin/**/*
    - tmp/**/*
    - vendor/**/*
    - db/migrate/**/*
    - db/schema.rb
  DisplayCopNames: true
  TargetRubyVersion: 2.2

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 16
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 15
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Style/VariableNumber:
  EnforcedStyle: snake_case

Rails:
  Enabled: true

Style/SignalException:
  EnforcedStyle: only_raise

Style/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space

Style/StringLiterals:
  EnforcedStyle: double_quotes
