AllCops:
  Exclude:
    - bin/**/*
    - tmp/**/*
    - vendor/**/*
    - db/migrate/**/*
    - db/schema.rb
  DisplayCopNames: true
  TargetRubyVersion: 2.2

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
Metrics/AbcSize:
  Max: 16

Rails:
  Enabled: true

Style/SignalException:
  EnforcedStyle: only_raise

Style/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space

Style/StringLiterals:
  EnforcedStyle: double_quotes
