AllCops:
  Exclude:
    - bin/**/*
    - tmp/**/*
    - vendor/**/*
  DisplayCopNames: true
  RunRailsCops: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/SignalException:
  EnforcedStyle: only_raise

Style/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space

Style/StringLiterals:
  EnforcedStyle: double_quotes
