default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['STOCKAID_DATABASE_USERNAME'] %>
  password: <%= ENV['STOCKAID_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: stockaid_development
  host: localhost

test:
  <<: *default
  database: stockaid_test

production:
  <<: *default
  database: stockaid_production
